### PR TITLE
FEATURE: Support copyright notice

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
See also

- https://github.com/neos/metadata-extractor/pull/22
- https://github.com/neos/metadata-contentrepositoryadapter/pull/7

**Review by daniellienert — CHANGES_REQUESTED** [review]
We need to change the minimum requirement to Neos 4.2. (Also needed in the extractor which I sadly already released)

**Comment by kdambekalns** [comment]
> We need to change the minimum requirement to Neos 4.2

Why? The package only depends on  Flow… but to be correct, it should actually have a dependency on neos/media added, and that needs to be 4.2 (for copyright notice support).

Even though the non-Asset-mapping related part could work without that (well, needs neos/media, but could skip copyright notice handling).

WDYT?

**Comment by daniellienert** [comment]
Dependency to flow is wrong obviously. As you use a setter on asset which is only available in 4.2 we need a dep to that

**Comment by kdambekalns** [comment]
@daniellienert Ok, this is what I meant:

- keep dependency on Flow (we use that)
- add dependency on Media (we use that and it was removed with https://github.com/neos/metadata/commit/e89588245aee6d1cd2120e084be3dcf1f5c01919, probably an oversight)
- but keep it as `"neos/media": "^3.0 || ^4.0"` and in the `AssetModelMetaDataMapper` do this:
  ```php
  if (isset($this->metaDataMappingConfiguration['copyrightNotice']) && method_exists($asset, 'setCopyrightNotice')) {
          $asset->setCopyrightNotice((string)EelUtility::evaluateEelExpression($this->metaDataMappingConfiguration['copyrightNotice'], $this->eelEvaluator, $contextVariables));
  }
  ```

That way it stays compatible without raising the dependency, thus keeping older versions (especially Neos 4.0 and 4.1) in the loop when it comes to further potential fixes/features.

**Review by daniellienert — APPROVED** [review]

**Pull request merged**
